import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BookProvider } from "./context/BookContext";
import { AuthProvider } from "./context/AuthContext"; 
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Book Order",
  description: "Book ordering web app generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <BookProvider>
            {children}
            <ToastContainer />
          </BookProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
